namespace OsuClient.Tests.Beatmaps
{
    /// <summary>
    /// In-memory .osu fixtures. Nothing here touches the disk or the network,
    /// so every test is deterministic.
    /// </summary>
    public static class TestBeatmapFixtures
    {
        /// <summary>
        /// Verbatim output of the Python backend's
        /// <c>src/export/osu_writer.py: render_beatmap()</c> — generated by
        /// running it, not written by hand, so this is a golden fixture of what
        /// the frontend actually has to read.
        ///
        /// Contents: two circles, a 1-slide slider, a 2-slide slider, a spinner,
        /// and a circle after a long rest. 128 BPM (beat length 468.75 ms),
        /// offset 123 ms, SliderMultiplier 1.4 (so 140 osu!pixels per beat).
        /// New-combo flags land on object 0 (first) and object 5 (after the
        /// spinner), which is exactly the backend's rule.
        /// </summary>
        public const string BackendGenerated =
            """
            osu file format v14

            [General]
            AudioFilename:audio.mp3
            AudioLeadIn:0
            PreviewTime:-1
            Countdown:0
            SampleSet:Normal
            StackLeniency:0.7
            Mode:0
            LetterboxInBreaks:0
            WidescreenStoryboard:0

            [Editor]
            DistanceSpacing:1.0
            BeatDivisor:4
            GridSize:4
            TimelineZoom:1.0

            [Metadata]
            Title:Test Song
            TitleUnicode:Test Song
            Artist:Test Artist
            ArtistUnicode:Test Artist
            Creator:osu-dsp-generator
            Version:Hard
            Source:
            Tags:dsp generated procedural
            BeatmapID:0
            BeatmapSetID:-1

            [Difficulty]
            HPDrainRate:5.0
            CircleSize:4.0
            OverallDifficulty:7.0
            ApproachRate:8.5
            SliderMultiplier:1.4
            SliderTickRate:1

            [Events]
            //Background and Video events
            //Break Periods
            //Storyboard Layer 0 (Background)
            //Storyboard Layer 1 (Fail)
            //Storyboard Layer 2 (Pass)
            //Storyboard Layer 3 (Foreground)
            //Storyboard Layer 4 (Overlay)
            //Storyboard Sound Samples

            [TimingPoints]
            123,468.750000,4,1,0,70,1,0

            [HitObjects]
            100,120,500,5,0,0:0:0:0:
            180,141,969,1,0,0:0:0:0:
            256,192,1438,2,0,L|320:220,1,140.00,0|0,0:0|0:0,0:0:0:0:
            300,100,2000,2,0,L|360:150,2,105.00,0|0|0,0:0|0:0|0:0,0:0:0:0:
            256,192,3500,8,0,5500,0:0:0:0:
            200,200,8000,5,0,0:0:0:0:
            """;

        /// <summary>The smallest file the decoder should accept: header plus nothing.</summary>
        public const string HeaderOnly = "osu file format v14\n";

        /// <summary>
        /// A minimal map used where the full fixture would be noise. One red
        /// line at 1000 ms per beat (60 BPM) and SliderMultiplier 1.0, so a
        /// 100-pixel slider is exactly one beat.
        /// </summary>
        public const string Minimal =
            """
            osu file format v14

            [General]
            AudioFilename:song.mp3

            [Difficulty]
            HPDrainRate:5
            CircleSize:4
            OverallDifficulty:6
            ApproachRate:9
            SliderMultiplier:1
            SliderTickRate:1

            [TimingPoints]
            0,1000,4,1,0,70,1,0

            [HitObjects]
            256,192,0,1,0,0:0:0:0:
            """;

        /// <summary>Builds a one-object map around a raw [HitObjects] record.</summary>
        public static string WithHitObject(string record) =>
            "osu file format v14\n"
            + "\n[Difficulty]\nSliderMultiplier:1\n"
            + "\n[TimingPoints]\n0,1000,4,1,0,70,1,0\n"
            + "\n[HitObjects]\n" + record + "\n";
    }
}
